videolist = [
    {"imgsrc":"carousel/imgs/1.png","videosrc":"http://static.youku.com/v/swf/qplayer.swf?VideoIDS=XOTIxNTUxMDIw=&isAutoPlay=true&isShowRelatedVideo=false&embedid=-&showAd=0",
        "head":"Mom of a Special Daughter",
        "headerinfo":"<p>Alumni Interview Series: Yuan Liu, Mom of a Special Daughter</p><time datetime='2015-03-28'>March 28, 2015</time>",
        "footerinfo": "<div class='post-item-injection'></div> <div class='entry-info'> </div> <div class='engagement'> <a href='http://www.xiaophotography.com/blog/2015/3/28/alumni-interview-series-yuan-liu-mom-of-a-special-daughter#comments-placeholder' data-toggle-target='#comments-placeholder' class='comment-link'>Comment </a> <span class='sqs-simple-like' data-item-id='5516aef2e4b00e328413be08' data-like-count='1' id='yui_3_17_2_1_1428905884326_431'><span class='like-icon'></span><span class='like-count'>1 Like</span></span> <span class='squarespace-social-buttons inline-style' data-system-data-id='1427550267276-CRT67AU37ODJHW4EKAN0' data-asset-url='http://static1.squarespace.com/static/542eb7fee4b01c92dfeece71/548c8c64e4b0b330492e9070/5516aef2e4b00e328413be08/1427722863716/' data-record-type='1' data-full-url='/blog/2015/3/28/alumni-interview-series-yuan-liu-mom-of-a-special-daughter' data-title='Alumni Interview Series: Yuan Liu, Mom of a Special Daughter '> <div id='social-yui_3_17_2_1_1428905884326_449' class='yui3-widget yui3-socialbutton'> <div id='yui_3_17_2_1_1428905884326_462' class='yui3-socialbutton-content'> <div class='ss-social-list-wrapper'> <div class='ss-social-button-list'></div> </div> </div> </div> </span> </div>",
        "content":'https://i.ytimg.com/vi_webp/9Qh9mPzQyKk/sddefault.webp<p>Youku:</p> <p> <a target="_blank" href="http://v.youku.com/v_show/id_XOTIxNTUxMDIw.html">http://v.youku.com/v_show/id_XOTIxNTUxMDIw.html</a></p> <p>&nbsp;</p> <p>Thanks "<a target="_blank" href="http://www.nytimes.com/packages/html/nyregion/1-in-8-million/">One in Eight Million</a>" for inspiration.</p>'
    },
    {"imgsrc":"carousel/imgs/2.png","videosrc":"http://static.youku.com/v/swf/qplayer.swf?VideoIDS=XODkzNDg4OTQ4=&isAutoPlay=true&isShowRelatedVideo=false&embedid=-&showAd=0",
        "head":"A Life of Games",
        "headerinfo":'<p>Alumni Interview Series: Honghao Zhu, A Life of Games</p><time datetime="2015-02-14">February 14, 2015</time>in documentary,alumni interview series',
        "footerinfo":'<div class="post-item-injection"></div><div class="entry-info"> <span class="tags">Tags: <a href="http://www.xiaophotography.com/blog/?tag=tsinghua#show-archive" rel="tag">tsinghua</a>, <a href="http://www.xiaophotography.com/blog/?tag=gavin#show-archive" rel="tag">gavin</a>, <a href="http://www.xiaophotography.com/blog/?tag=video+games#show-archive" rel="tag">video games</a>, <a href="http://www.xiaophotography.com/blog/?tag=inter#show-archive" rel="tag">inter</a></span></div> <div class="engagement"> <a href="http://www.xiaophotography.com/blog/2015/2/14/alumni-interview-series-honghao-zhu-a-life-of-games#comments-placeholder" data-toggle-target="#comments-placeholder" class="comment-link"> Comment</a> <span class="sqs-simple-like" data-item-id="54df6009e4b0f4a6ba2c9745" data-like-count="0" id="yui_3_17_2_1_1428905884326_434"><span class="like-icon"></span><span class="like-count">0 Likes</span></span> <span class="squarespace-social-buttons inline-style" data-system-data-id="1423925535879-O9Q8AEHJ2UNSOSG7FPHX" data-asset-url="http://static1.squarespace.com/static/542eb7fee4b01c92dfeece71/548c8c64e4b0b330492e9070/54df6009e4b0f4a6ba2c9745/1423925547205/" data-record-type="1" data-full-url="/blog/2015/2/14/alumni-interview-series-honghao-zhu-a-life-of-games" data-title="Alumni Interview Series: Honghao Zhu, A Life of Games"><div id="social-yui_3_17_2_1_1428905884326_451" class="yui3-widget yui3-socialbutton"><div id="yui_3_17_2_1_1428905884326_476" class="yui3-socialbutton-content"><div class="ss-social-button-wrapper"><div class="ss-social-button"><span class="ss-social-button-icon"></span>Share</div></div><div class="ss-social-list-wrapper"><div class="ss-social-button-list"></div></div></div></div></span> </div>',
        "content":'https://i.ytimg.com/vi_webp/zR2rBK4cLtI/sddefault.webp<p>朱洪浩，06级，人文学院日语系。</p> <p>亲爱的小师弟，在他快要离开美国的时候对他内心的游戏世界有了更多的了解。游戏于他，不只是调剂和放松，更是生活的浓缩和心心念念的梦想。愿未来的游戏之路充满快乐。</p> <p>优酷链接：http://v.youku.com/v_show/id_XODkzNDg4OTQ4.html</p><p>Thanks "One in Eight Million" for inspirations.</p>'
    },
    {"imgsrc":"carousel/imgs/3.png","videosrc":"http://static.youku.com/v/swf/qplayer.swf?VideoIDS=XOTM0MjU5OTQ4=&isAutoPlay=true&isShowRelatedVideo=false&embedid=-&showAd=0",
        "head":"a Hotel Enthusiast",
        "headerinfo":'<p>Alumni Interview Series: Leo Liao, a Hotel Enthusiast</p><time datetime="2015-02-06">February 06, 2015</time>in alumni interview series',
        "footerinfo":'<div class="post-item-injection"></div> <div class="entry-info"> <span class="tags">Tags: <a href="http://www.xiaophotography.com/blog/?tag=leo#show-archive" rel="tag">leo</a>, <a href="http://www.xiaophotography.com/blog/?tag=tsinghua#show-archive" rel="tag">tsinghua</a>, <a href="http://www.xiaophotography.com/blog/?tag=interview#show-archive" rel="tag">interview</a>, <a href="http://www.xiaophotography.com/blog/?tag=hotel#show-archive" rel="tag">hotel</a>, <a href="http://www.xiaophotography.com/blog/?tag=capella#show-archive" rel="tag">capella</a>, <a href="http://www.xiaophotography.com/blog/?tag=georgetown#show-archive" rel="tag">georgetown</a></span></div><div class="engagement"> <a href="http://www.xiaophotography.com/blog/2015/2/6/alumni-interview-series-leo-a-hotel-enthusiast#comments-placeholder" data-toggle-target="#comments-placeholder" class="comment-link"> Comment</a><span class="sqs-simple-like" data-item-id="54d53994e4b0237ad2e730a1" data-like-count="2" id="yui_3_17_2_1_1428905884326_437"><span class="like-icon"></span><span class="like-count">2 Likes</span></span> <span class="squarespace-social-buttons inline-style" data-system-data-id="1423266841290-1ZABSVWX7EFVTDDVP1B3" data-asset-url="http://static1.squarespace.com/static/542eb7fee4b01c92dfeece71/548c8c64e4b0b330492e9070/54d53994e4b0237ad2e730a1/1423782555738/" data-record-type="1" data-full-url="/blog/2015/2/6/alumni-interview-series-leo-a-hotel-enthusiast" data-title="Alumni Interview Series: Leo Liao, a Hotel Enthusiast "><div id="social-yui_3_17_2_1_1428905884326_453" class="yui3-widget yui3-socialbutton"><div id="yui_3_17_2_1_1428905884326_490" class="yui3-socialbutton-content"><div class="ss-social-button-wrapper"><div class="ss-social-button"><span class="ss-social-button-icon"></span>Share</div></div><div class="ss-social-list-wrapper"><div class="ss-social-button-list"></div></div></div></div></span> </div>',
        "content":'https://i.ytimg.com/vi_webp/YsUrKMaChDs/hqdefault.webp<p>Thanks One in Eight Million for inspiration.</p>'
    },
    {"imgsrc":"carousel/imgs/4.png","videosrc":"http://static.youku.com/v/swf/qplayer.swf?VideoIDS=XODc4MzgzNTMy=&isAutoPlay=true&isShowRelatedVideo=false&embedid=-&showAd=0",
        "head":"Ru Ding &amp; Yun Zhang",
        "headerinfo":'<p>Alumni Interview Series: Ru Ding &amp; Yun Zhang</p><time datetime="2015-01-23">January 23, 2015</time>in documentary alumni interview series',
        "footerinfo":' <div class="post-item-injection"></div> <div class="entry-info"> <span class="tags">Tags: <a href="http://www.xiaophotography.com/blog/?tag=boston#show-archive" rel="tag">boston</a>, <a href="http://www.xiaophotography.com/blog/?tag=tsinghua#show-archive" rel="tag">tsinghua</a>, <a href="http://www.xiaophotography.com/blog/?tag=peking+university#show-archive" rel="tag">peking university</a>, <a href="http://www.xiaophotography.com/blog/?tag=love#show-archive" rel="tag">love</a></span></div> <div class="engagement"> <a href="http://www.xiaophotography.com/blog/2015/1/23/ru-ding-jian-fang#comments-placeholder" data-toggle-target="#comments-placeholder" class="comment-link"> Comment </a> <span class="sqs-simple-like" data-item-id="54c2e3fae4b01ba65f57bc0e" data-like-count="4" id="yui_3_17_2_1_1428905884326_440"><span class="like-icon"></span><span class="like-count">4 Likes</span></span> <span class="squarespace-social-buttons inline-style" data-system-data-id="" data-asset-url="http://static1.squarespace.com/static/542eb7fee4b01c92dfeece71/548c8c64e4b0b330492e9070/54c2e3fae4b01ba65f57bc0e/1423782578722/" data-record-type="1" data-full-url="/blog/2015/1/23/ru-ding-jian-fang" data-title="Alumni Interview Series: Ru Ding &amp; Yun Zhang"><div id="social-yui_3_17_2_1_1428905884326_455" class="yui3-widget yui3-socialbutton"><div id="yui_3_17_2_1_1428905884326_504" class="yui3-socialbutton-content"><div class="ss-social-button-wrapper"><div class="ss-social-button"><span class="ss-social-button-icon"></span>Share</div></div><div class="ss-social-list-wrapper"><div class="ss-social-button-list"></div></div></div></div></span> </div>',
        "content":'https://i.ytimg.com/vi_webp/yOLfAIEuP3E/hqdefault.webp<p>A love story between a Tsinghua girl and a PKU Boy.</p><p>Youku:&nbsp;http://v.youku.com/v_show/id_XODc4MzgzNTMy.html</p><p>Thanks One in Eight Million for inspiration.</p>'
    },
    {"imgsrc":"carousel/imgs/5.png","videosrc":"http://static.youku.com/v/swf/qplayer.swf?VideoIDS=XODQ4MjMyNDcy=&isAutoPlay=true&isShowRelatedVideo=false&embedid=-&showAd=0",
        "head":"A Soccer Dad",
        "headerinfo":' <p>Alumni Interview Series: Jian Fang, A Soccer Dad</p><time datetime="2014-12-13">December 13, 2014</time>in documentary alumni interview series',
        "footerinfo":'  <div class="post-item-injection"></div><div class="entry-info"> <span class="tags">Tags: <a href="http://www.xiaophotography.com/blog/?tag=documentary#show-archive" rel="tag">documentary</a>, <a href="http://www.xiaophotography.com/blog/?tag=soccer#show-archive" rel="tag">soccer</a>, <a href="http://www.xiaophotography.com/blog/?tag=tsinghua#show-archive" rel="tag">tsinghua</a>, <a href="http://www.xiaophotography.com/blog/?tag=jian+fang#show-archive" rel="tag">jian fang</a>, <a href="http://www.xiaophotography.com/blog/?tag=alex#show-archive" rel="tag">alex</a></span></div> <div class="engagement"> <a href="http://www.xiaophotography.com/blog/2014/12/13/jian-fang-a-soccer-dad#comments-placeholder" data-toggle-target="#comments-placeholder" class="comment-link"> Comment </a> <span class="sqs-simple-like" data-item-id="548c8f23e4b00591d4b1c2de" data-like-count="3" id="yui_3_17_2_1_1428905884326_443"><span class="like-icon"></span><span class="like-count">3 Likes</span></span><span class="squarespace-social-buttons inline-style" data-system-data-id="" data-asset-url="http://static1.squarespace.com/static/542eb7fee4b01c92dfeece71/548c8c64e4b0b330492e9070/548c8f23e4b00591d4b1c2de/1423260428752/" data-record-type="1" data-full-url="/blog/2014/12/13/jian-fang-a-soccer-dad" data-title="Alumni Interview Series: Jian Fang, A Soccer Dad"><div id="social-yui_3_17_2_1_1428905884326_457" class="yui3-widget yui3-socialbutton"><div id="yui_3_17_2_1_1428905884326_518" class="yui3-socialbutton-content"><div class="ss-social-button-wrapper"><div class="ss-social-button"><span class="ss-social-button-icon"></span>Share</div></div><div class="ss-social-list-wrapper"><div class="ss-social-button-list"></div></div></div></div></span> </div>',
        "content":'https://i.ytimg.com/vi_webp/z8ReVRaUd1k/hqdefault.webp<p>Jian Fang, class of 99, Chemical Engineering, Tsinghua University. Jian has came to U.S. for over 10 years since 2003. As a father of two, his passion for soccer has only increased with his love toward the family.</p><h3>Video on Youku</h3><p>http://v.youku.com/v_show/id_XODQ4MjMyNDcy.html</p><blockquote>In honor of the NYT series, "<a target="_blank" href="http://www.nytimes.com/packages/html/nyregion/1-in-8-million/"><em>One in Eight Million</em></a>".</blockquote>'
    }
];

